import { Product } from "@/types/product";

export const productsData: Product[] = [
  // ==================== MACHINES - LASER ====================
  {
    id: "bison-dual-accento",
    name: "Bison Dual Accento - Dual Alexandrite Laser",
    brand: "Bison",
    category: "Machines",
    subcategory: "Laser",
    description: "Dual Accento is the unique device combining 755nm Long pulsed Alexandrite and 1064nm Long pulsed Nd:YAG. The combination of two different wavelengths makes Dual Accento the highly effective system for hair removal and pigmented lesions treatment. Nd:YAG 1064nm long pulsed wavelength rejuvenates the skin  by stimulating and collagen layer of the dermis and effectively treats vascular lesions.",
    features: [
      "755nm / 1064 Dual Pulsed Laser.",
      "Flat-TopBeam.",
      "High Repetition Rate (Frequency).",
      "Auto-Calibration System.",
      "Cooling Spray or Air Cryo System.",
      "Addtional dual display synchronized with camera.",
      "High Energy.",
      "Adjustable Spot Size.",
    ],
    images: ["/images/products/Machines/Laser/Bison Dual Accento/1.png"],
  },
  {
    id: "bison-lucid-q-ptp",
    name: "Bison Lucid Q-PTP - Nd YAG Q-SWITCHED",
    brand: "Bison",
    category: "Machines",
    subcategory: "Laser",
    description: "LUCID Q-PTP has two wavelengths of 1064nm and 532nm. To reduce side effects of high energy, it adopts PTP mode which divides the high energy into two pulses with very short duration. LUCID Q-PTPT effectively reduces pigmented lesions on dermis and epidermis and also minimizes the risk of side effects such as hypopigmentation, pigmentation and recurrence of Malesma, comparing to previous laser toning procedures.",
    features: [
      "High repetition rate (frequency).",
      "Auto-Calibration System.",
      "Q-PTP mode.",
      "Quasi-Long Mode.",
      "Durability.",
      "High pulse frequency.",
    ],
    images: ["/images/products/Machines/Laser/Bison Lucid Q-PTP/1.png"],
  },
  {
    id: "picocare-250",
    name: "PicoCare 250",
    brand: "PicoCare",
    category: "Machines",
    subcategory: "Laser",
    description: "WORLD’S FIRST 250 PICOSECOND LASER 250 Picosencond 1064 nm & 532 nm Nd:YAG Laser",
    features: [
      
    ],
    images: [
        "/images/products/Machines/Laser/Picocare 250/1.png",
        "/images/products/Machines/Laser/Picocare 250/2.png",
        "/images/products/Machines/Laser/Picocare 250/3.png",
        "/images/products/Machines/Laser/Picocare 250/4.png",
        "/images/products/Machines/Laser/Picocare 250/5.png",
    ],
  },
  {
    id: "picocare-450",
    name: "PicoCare 450",
    brand: "PicoCare",
    category: "Machines",
    subcategory: "Laser",
    description: "Bringing better results with no side e ects in tattoo removal and pigmentation treatment. Epidermal lesions – Dermal lesions – Hexa mla (acne scar, skin rejuvenation)",
    features: [
      "Picosecond Nd:Yag laser 1064nm&532nm + 595nm, 660nm.",
      "Beyond nano, experience real pico: Picocare breaks all tattoos colours and pigments into tiny particles by higher peak power of shorter pulse duration.",
      "Best solution for tattoo removal More photomechanical effect with less thermal effect on the skin. Better results with almost no side effects",
      "Hexa mla handpiece, replacing subcision: Hexa mla (micro lens array) handpiece is the fractional system with high energy density in the center of each dots. With this handpiece, picocare can replace aggressive scar treatments,  scar tissues can be destroyed without severe pain",
    ],
    images: [
        "/images/products/Machines/Laser/Picocare 450/1.png",
        "/images/products/Machines/Laser/Picocare 450/2.png",
        "/images/products/Machines/Laser/Picocare 450/3.png",
        "/images/products/Machines/Laser/Picocare 450/4.png",
        "/images/products/Machines/Laser/Picocare 450/5.png",
    ],
  },
  {
    id: "primelase-hr",
    name: "Primelase HR",
    brand: "Primelase HR",
    category: "Machines",
    subcategory: "Laser",
    description: "The 1st and only laser device combining di erent wave lengths to perform on all skin types. 4 wavelengths Alexandrite - Blended - Nd:Yag - Diode. 4 spot sizes 20x9mm - 30x9mm - 30x17mm. PAINLESS DIODE LASER HAIR REMOVAL SYSTEM WITH ALEXANDRITE AND ND: YAG TECHNOLOGIES",
    features: [
      "High peak power: 4.800w, highest in the market.",
      "Painless hair removal.",
      "Suits all skin and hair types, all-year round.",
      "Instant results from the first session.",
      "2 modes: static and dynamic.",
      "Constant cooling system for stable temperature of 5° c.",
    ],
    images: [
        "/images/products/Machines/Laser/Primelase HR/1.png",
        "/images/products/Machines/Laser/Primelase HR/2.png",
        "/images/products/Machines/Laser/Primelase HR/3.png",
        "/images/products/Machines/Laser/Primelase HR/4.png",
        "/images/products/Machines/Laser/Primelase HR/5.png",
        "/images/products/Machines/Laser/Primelase HR/6.png",
    ],
  },

  // ==================== MACHINES - AESTHETIC ====================
  {
    id: "forza",
    name: "Forza Laser",
    brand: "Aesthetic Solution Dermaqual Paris",
    category: "Machines",
    subcategory: "Aesthetic",
    description: "FORZA LASER is an FDA-Approved revolutionary platform that effectively eliminates stubborn fat while enhancing body contours and sculpting an ideal physique.This advanced procedure utilizes innovative alternatives to traditional liposuction, delivering astonishing and naturallooking results.With its competitive pricing and exceptional outcomes, many physicians favor FORZA LAZER as the optimal choice for fat reduction and body shaping.",
    features: [
      "Improved skin tightening.",
      "A dramatic improvement in the appearance of unwanted fat.",
      "A swift recovery, with most patients returning to work the very next day.",
      "Fast and enhanced treatment results.",
    ],
    images: ["/images/products/Machines/Aesthetic/Forza/1.png"],
  },
  {
    id: "pal-microaire",
    name: "PAL Microaire",
    brand: "PAL Microaire",
    category: "Machines",
    subcategory: "Aesthetic",
    description: "The innovative Pal Liposculptor is the only U.S.-patented Liposuction instrument using a reciprocating motion (rather than rotating) to facilitate the movement of the cannula, gliding through fibrous tissue more easily.",
    features: [
      "Less bruising and bleeding ",
      "Stem cell and lipofilling possibilities",
      "Fast procedure",
    ],
    images: [
        "/images/products/Machines/Aesthetic/PAL microaire/1.png",
        "/images/products/Machines/Aesthetic/PAL microaire/2.png",
        "/images/products/Machines/Aesthetic/PAL microaire/3.png"
    ],
  },
  {
    id: "smart-sonic",
    name: "Smart Sonic",
    brand: "Smart Sonic",
    category: "Machines",
    subcategory: "Aesthetic",
    description: "A tight-focused ultrasonic, non-invasive and non-surgical face lifting and body slimming system. It is a multiple skin care system that combines the functions of lifting, elasticity, and tightening. ",
    features: [
      "Face and Body Lifting",
      "Skin Rejuvenation",
      "Skin Tightening",
      "Wrinkles – Fine Lines Treatment",
      "Double-Chin treatment",
      "Body Shaping Fat Reduction",
    ],
    images: [
        "/images/products/Machines/Aesthetic/Smart Sonic/1.png",
        "/images/products/Machines/Aesthetic/Smart Sonic/2.png",
        "/images/products/Machines/Aesthetic/Smart Sonic/3.png"
        ],
  },
  {
    id: "venus-viva",
    name: "Venus Viva",
    brand: "Venus Viva",
    category: "Machines",
    subcategory: "Aesthetic",
    description: "The first and only fractional radio frequency ( RF ) system allows operator control of ablation and coagulation for enhanced e cacy in resolving mild to severe skin damage.",
    features: [
      "Highly customizable parameters for wide range of skin conditions.",
      "Reduce signs of skin damage.",
      "High patient satisfaction.",
      "Nonfractional RF applicator.",
      "Skin Resurfacing.",
      "Acne scares & Rosea.",
      "Enlarged pores & deep wrinkles.",
      "Stretch marks & pigmentation.",
      "Dyschromia & uneven texture.",
    ],
    images: [
        "/images/products/Machines/Aesthetic/Venus Viva/1.png",
        "/images/products/Machines/Aesthetic/Venus Viva/2.png",
        "/images/products/Machines/Aesthetic/Venus Viva/3.png"
    ],
  },

  // ==================== MACHINES - FACIAL ====================
  {
    id: "hydracool",
    name: "HydraCool",
    brand: "HydraCool",
    category: "Machines",
    subcategory: "Facial",
    description: "8 in 1 system for perfect skin & scalp care Hydracool is the multi-function skin treatment device",
    features: [
      "8 Applicators for Best Skin Care",
      "Various Preset Programs",
      "Powerful Oxygen Compressor",
      "Simple & Easy Operation",
      "Simultaneous Use at 2 Modes",
      "Modern Design",
    ],
    images: [
        "/images/products/Machines/Facial/HydraCool/1.png",
        "/images/products/Machines/Facial/HydraCool/2.png"
    ],
  },
  {
    id: "hydracool-plus",
    name: "HydraCool Plus",
    brand: "HydraCool Plus",
    category: "Machines",
    subcategory: "Facial",
    description: "The 4-in-1 Skin Management System combines advanced technologies to deliver deep cleansing, rejuvenation, and skin renewal. AquaB Technology allows water molecules to penetrate the skin directly, providing deep cleansing, improving skin texture, and effectively removing blackheads. ViborX Technology enhances oxygen levels in blood circulation, revitalizing skin cells to promote rejuvenation, skin tightening, and the reduction of wrinkles and fine lines. Collagen+ Technology uses radio frequency (RF) to evenly heat collagen, stimulating skin regeneration and lifting sagging skin. Finally, UltraB Technology breaks down the molecular structure of moisturizing and hydrating products into smaller particles, allowing them to penetrate deeper into the skin for maximum hydration and nourishment.",
    features: [
      "Deep Cleaning.",
      "Skin Lightening.",
      "Wrinkle Reduction.",
      "Skin Tightening.",
    ],
    images: [
        "/images/products/Machines/Facial/HydraCoolPlus/1.png",
        "/images/products/Machines/Facial/HydraCoolPlus/2.png",
        "/images/products/Machines/Facial/HydraCoolPlus/3.png",
        "/images/products/Machines/Facial/HydraCoolPlus/4.png",
        "/images/products/Machines/Facial/HydraCoolPlus/5.png",
    ],
  },
  {
    id: "minivac",
    name: "Minivac",
    brand: "Minivac",
    category: "Machines",
    subcategory: "Facial",
    description: "The Most Renowned Equipment on Diamond Microdermabrasion. Using many heads of diamonds, Minivac eliminates dead cells, renews the skin, and gives strong shiny results without causing harm to the skin.",
    features: [
      "No Side Effects.",
      "Direct Results.",
      "Removes dead cells and pigmentation.",
    ],
    images: [
        "/images/products/Machines/Facial/Minivac/1.png",
        "/images/products/Machines/Facial/Minivac/2.png",
        "/images/products/Machines/Facial/Minivac/3.png",
    ],
  },
  {
    id: "o2toderm",
    name: "O2toDerm",
    brand: "O2toDerm",
    category: "Machines",
    subcategory: "Facial",
    description: "OtoDerm is an oxygen anion generator which generates about three million anions (per cubic cm) of pure oxygen sucking in the air. Prevents aging caused by active oxygen, regeneration of damaged cells, improving immune system and protecting skin from toxic substances and bringing vitality into skin.",
    features: [
      "Oxygen Therapy: A cooling effect of oxygen shrinks expanded pores, reduces pain, and is effective for calming your skin.",
      "Anion Therapy: High concentrations of anions are supplied to the body by skin respiration with the forests healing effects and prevent to aging.",
      "Deep hydration.",
      "Oxygen Ampoule Therapy: High concentrated oxygen and ampoule help to provide collagen regeneration, moisture, nourishment and to brighten to skin deeply without irritation as spraying method in a cosmeceutical way",
    ],
    images: ["/images/products/Machines/Facial/O2toDerm/1.png"],
  },
  {
    id: "preime-facial",
    name: "Preime Facial Device",
    brand: "Preime",
    category: "Machines",
    subcategory: "Facial",
    description: "Introducing the Préime DermaFacial the world’s most advanced aesthetic facial device.  ",
    features: [
      "Cleanse & Infuse.",
      "Exfoliate & Revive.",
      "Tighten and Tone.",
      "Boost and Rejuvenate.",
      "Nourish & Moisture.",
    ],
    images: [
        "/images/products/Machines/Facial/Preime/1.png",
        "/images/products/Machines/Facial/Preime/2.png",
        "/images/products/Machines/Facial/Preime/3.png",
        "/images/products/Machines/Facial/Preime/4.png",
        "/images/products/Machines/Facial/Preime/5.png",
        "/images/products/Machines/Facial/Preime/6.png",
    ],
  },
  {
    id: "targetcool",
    name: "TargetCool Ice Needling",
    brand: "TargetCool",
    category: "Machines",
    subcategory: "Facial",
    description: "TargetCool is a non-contact non-invasive skin cooling medical device that can maximize the effectiveness of cosmetic procedures such as Botox and Fillers by reducing pain, inflammation, and swelling.",
    features: [
      "Non-contact, non-invasive skin cooling.",
      "Reduces pain during cosmetic procedures.",
      "Minimizes inflammation and swelling.",
      "Precision-targeted cooling.",
      "Enhances effectiveness of Botox and fillers.",
      "Improves patient comfort.",
      "Hygienic and safe technology.",
    ],
    images: ["/images/products/Machines/Facial/TargetCool/1.png"],
  },

  // ==================== MACHINES - SLIMMING ====================
  {
    id: "cooltech",
    name: "Cooltech",
    brand: "Cooltech",
    category: "Machines",
    subcategory: "Slimming",
    description: "LOCALIZED FAT REDUCTION. Effectively reduces localized adipose tissue using a controlled cooling system.",
    features: [
      "Safe and effective.",
      "Pain free and non-invasive.",
      "Visible results starting 15 days after one procedure.",
      "Allows an immediate incorporation to the patient’s daily life.",
      "2 independent applicators .",
      "Up to 25% localized fat reduction in one session.",
    ],
    images: [
      "/images/products/Machines/Slimming/Cooltech/1.png",
      "/images/products/Machines/Slimming/Cooltech/2.png",
      "/images/products/Machines/Slimming/Cooltech/3.png",
      "/images/products/Machines/Slimming/Cooltech/4.png",
      "/images/products/Machines/Slimming/Cooltech/5.png",
      "/images/products/Machines/Slimming/Cooltech/6.png",
      "/images/products/Machines/Slimming/Cooltech/7.png",
    ],
  },
  {
    id: "cooltech-define",
    name: "Cooltech Define",
    brand: "Cooltech",
    category: "Machines",
    subcategory: "Slimming",
    description: "CRYOADIPOLYSIS - Safe and effective treatment, which allows to achieve excellent results and high profitability in a very short time.",
    features: [
      "Accurate diagnosis.",
      "4 simultaneous applicators in one session.",
      "360º complete cooling of the treated area.",
      "9 different applicators that fit perfectly.",
      "9 treatment templates.",
      "Up to 30% Localized fat reduction in 1 session.",
    ],
    images: [
        "/images/products/Machines/Slimming/Cooltech Define/1.png",
        "/images/products/Machines/Slimming/Cooltech Define/2.png",
        "/images/products/Machines/Slimming/Cooltech Define/3.png",
        "/images/products/Machines/Slimming/Cooltech Define/4.png",
        "/images/products/Machines/Slimming/Cooltech Define/5.png",
        "/images/products/Machines/Slimming/Cooltech Define/6.png",
        "/images/products/Machines/Slimming/Cooltech Define/7.png",
    ],
  },
  {
    id: "venus-legacy",
    name: "Venus Legacy",
    brand: "Venus Legacy",
    category: "Machines",
    subcategory: "Slimming",
    description: "(MP)2 + VARIPULSE TECHNOLOGY - The Highly advanced non-invasive medical device that most e ectively resolves challenging face and body aesthetic needs, Such as non-surgical cellulite reduction and wrinkle reduction.",
    features: [
      "Innovative (MP)2 Technology.",
      "Synergetic combination of multi-polar frequency (RF) and pulsed electro magnetic fields (PEMF).",
      "Advanced Varipluse technology.",
      "Enhances the lipolysis effects of RF energy, increases blood circulation, and stimulated lymphatic drainage.",
      "Real-time thermal feedback.",
      "4 unique applicators.",
    ],
    images: [
        "/images/products/Machines/Slimming/Venus Legacy/1.png",
        "/images/products/Machines/Slimming/Venus Legacy/2.png",
        "/images/products/Machines/Slimming/Venus Legacy/3.png",
        "/images/products/Machines/Slimming/Venus Legacy/4.png",
        "/images/products/Machines/Slimming/Venus Legacy/5.png",
    ],
  },

  // ==================== MACHINES - SUPPORT ====================
  {
    id: "aurora-x2",
    name: "Aurora X2",
    brand: "Aurora X2",
    category: "Machines",
    subcategory: "Support",
    description: "AURORA X2 is the multi-body slimming system to treat the facial area and the body. AURORA X2 comes in three sizes of effectively designed applicators powered by proven RF, Vacuum Suction & LED technologies.",
    features: [

    ],
    images: ["/images/products/Machines/Support/Aurora X2/1.png"],
  },
  {
    id: "visbody",
    name: "VISBODY S30",
    brand: "Visbody",
    category: "Machines",
    subcategory: "Support",
    description: "AI-Powered 3D Body Scanner: Your Ultimate Body Composition & Posture Analysis The VisBody-S 30 uses hybrid technology, combining 3D body scanning and Bioelectrical Impedance Analysis (BIA) for comprehensive scans, making it ideal for gyms, wellness centers, and beauty clinics. Its advanced technology allows for a detailed analysis of body composition, including muscle mass, body fat, basal metabolism rate and water content.  The device is user-friendly, efficient, and accurate, making it an excellent tool for professionals in the health and wellness industry to provide personalized services and recommendations to their clients. With Visbody S30, you can optimize your body analysis and take the first step towards achieving your health and wellness goals.",
    features: [
      "FDA-Approved for Trusted Precision.",
      "Fusion technology——BIA+3D Modeling.",
      "Instant 3D Body Reconstruction.",
      "Comprehensive Body Assessment within 32s.",
      "18  Core Body Composition Metrics.",
      "14 Circumference Measurements.",
      "9 Posture Assessment for a Balanced You.",
      "4 Shoulder Joint Metrics for Complete Mobility Insight.",
      "Visualized Historical Reports for Measurable Progress.",
      "AI-Assisted Interpretation and Tailored Fitness/Nutrition Plans.",
      "Touch Screen and Gesture Control for a Seamless User Experience.",
    ],
    images: ["/images/products/Machines/Support/Visbody/1.png"],
  },
  {
    id: "exomind",
    name: "Exomind",
    brand: "Exomind",
    category: "Machines",
    subcategory: "Aesthetic",
    description: "Exomind is an advanced non-invasive brain stimulation and cognitive wellness device. Using targeted electromagnetic stimulation, it enhances mental clarity, focus, and cognitive performance. Designed for professional wellness and aesthetic clinics seeking to offer next-generation mind-body treatment programmes.",
    features: [
      "Non-invasive electromagnetic brain stimulation",
      "Enhances cognitive performance and mental clarity",
      "Suitable for wellness and aesthetic clinical settings",
      "Safe, comfortable, and scientifically validated protocol",
    ],
    images: ["/images/products/Machines/Aesthetic/Exomind/1.png"],
  },
  {
    id: "emsella",
    name: "Emsella",
    brand: "BTL",
    category: "Machines",
    subcategory: "Aesthetic",
    description: "Emsella is a breakthrough treatment for incontinence and confidence. A single session brings thousands of supramaximal pelvic floor muscle contractions, which are extremely important in muscle re-education of incontinent patients. Scientific research shows 95% of treated patients reported significant improvement in their quality of life.",
    features: [
      "Non-invasive pelvic floor strengthening",
      "Thousands of supramaximal contractions per session",
      "Clinically proven for incontinence treatment",
      "Fully clothed treatment — no disrobing required",
      "95% patient satisfaction rate",
    ],
    images: ["/images/products/Machines/Aesthetic/Emsella/1.png"],
  },
  {
    id: "ultherapy-prime",
    name: "Ultherapy Prime",
    brand: "Merz",
    category: "Machines",
    subcategory: "Facial",
    description: "Ultherapy Prime is the most advanced version of the world's only FDA-cleared, non-invasive procedure for lifting the brow, chin, neck and chest. Using micro-focused ultrasound with visualisation (MFU-V), it stimulates collagen production deep within the skin for a natural lift and tightening effect with lasting results.",
    features: [
      "FDA-cleared non-invasive lifting procedure",
      "Micro-focused ultrasound with real-time visualisation",
      "Targets brow, chin, neck and décolletage",
      "Stimulates deep collagen regeneration",
      "Natural-looking lift lasting 12–18 months",
    ],
    images: ["/images/products/Machines/Facial/Ultherapy/1.png"],
  },
  {
    id: "arosha",
    name: "Arosha",
    brand: "Arosha",
    category: "Machines",
    subcategory: "Slimming",
    description: "Arosha is an innovative body treatment system that combines professional bandaging with cutting-edge active ingredient delivery. The system uses a unique combination of biopolymer bandages, active serums and thermal activation to deliver intensive slimming, detoxifying and firming results for the body.",
    features: [
      "Professional biopolymer body bandage system",
      "Advanced active ingredient penetration technology",
      "Targets slimming, firming and detoxification",
      "Visible results from the first treatment session",
      "Suitable for spa, wellness and aesthetic clinics",
    ],
    images: ["/images/products/Machines/Slimming/Arosha/1.png"],
  },
  {
    id: "exilis-ultra-360",
    name: "Exilis Ultra 360",
    brand: "BTL",
    category: "Machines",
    subcategory: "Slimming",
    description: "Exilis Ultra 360 is a sophisticated aesthetic device that combines radiofrequency and ultrasound energies to simultaneously tighten skin and reduce fat. With 360° energy delivery, it treats the face and body with unmatched precision and comfort, delivering visible lifting, contouring and skin tightening results.",
    features: [
      "Combined radiofrequency and ultrasound technology",
      "360° energy delivery for uniform treatment",
      "Simultaneous skin tightening and fat reduction",
      "Treats face, neck, and body",
      "Non-invasive with no downtime",
    ],
    images: ["/images/products/Machines/Slimming/Exilis/1.png"],
  },

  {
    id: "emsculpt",
    name: "Emsculpt",
    brand: "BTL",
    category: "Machines",
    subcategory: "Aesthetic",
    description: "Emsculpt is the next step towards the future of non-invasive body shaping — delivering simultaneous muscle growth and fat disruption with no surgery and no downtime. Using high-intensity focused electromagnetic (HIFEM) technology, a single session induces thousands of powerful muscle contractions impossible to achieve through voluntary exercise.",
    features: [
      "Non-invasive body sculpting and muscle growth",
      "Simultaneous fat disruption and muscle building",
      "No surgery, no downtime required",
      "High-intensity focused electromagnetic technology",
      "Non-invasive buttock lift alternative",
      "Ideal for patients seeking muscle and fat improvement",
    ],
    images: ["/images/products/Machines/Aesthetic/Emsculpt/1.png"],
  },

  // ==================== AESTHETIC - AESTHETIC ====================
  {
    id: "exohealer-hb-plus",
    name: "Exohealer HB Plus",
    brand: "Exohealer",
    category: "Aesthetic",
    subcategory: "Aesthetic",
    description: "Innovative Scalp Booster: P198 ExoHealer Filcore HB Plus is a cutting-edge scalp treatment developed using exosome cell biotechnology. It combines a lyophilized exosome powder with an activating solvent to deliver potent regenerative effects, specifically targeting scalp and hair health.",
    features: [
      "High concentration of stem cell-derived exosomes.",
      "Promotes hair follicle health.",
      "Improves hair density.",
      "Helps combat hair loss.",
      "Rejuvenates and revitalizes the scalp.",
      "Supports overall scalp health.",
    ],
    images: [
      "/images/products/Aesthetic/Aesthetic/Exohealer/HB Plus/1.png",
      "/images/products/Aesthetic/Aesthetic/Exohealer/HB Plus/2.png",
    ],
  },
  {
    id: "exohealer-sb-plus",
    name: "Exohealer SB Plus",
    brand: "Exohealer",
    category: "Aesthetic",
    subcategory: "Aesthetic",
    description: "Filcore SB Plus is an innovative skin booster developed through exosome cell biotechnology. It combines a lyophilized exosome powder with an activating solvent to deliver potentregenerative and anti-inflammatory effects.",
    features: [
      "High concentration of stem cell–derived exosomes.",
      "Targets fine lines and wrinkles.",
      "Improves skin elasticity.",
      "Enhances skin radiance and reduces dullness.",
      "Addresses multiple signs of aging.",
      "Promotes overall skin rejuvenation and revitalization.",
    ],
    images: [
      "/images/products/Aesthetic/Aesthetic/Exohealer/SB Plus/1.png",
      "/images/products/Aesthetic/Aesthetic/Exohealer/SB Plus/2.png",
    ],
  },
  {
    id: "mct-technology",
    name: "MCT Technology",
    brand: "MCT",
    category: "Machines",
    subcategory: "Aesthetic",
    description: "MCT Technology is a new generation platform that stands out for its much higher growth factor concentration, remarkable ATP production and spectacular skin rejuvenation, tissue regeneration and aesthetic results. Tailor-made secretomes combined with photothermal biomodulation for next-level clinical outcomes.",
    features: [
      "Increment of growth factors.",
      "Improved Platelet Performance.",
      "Reduction of pain.",
      "ATP synthesis stimulation.",
      "Photothermal biomodulation technology.",
    ],
    images: ["/images/products/Machines/Aesthetic/MCT Technology/1.png"],
  },
  {
    id: "miracu",
    name: "Miracu Lifting Threads",
    brand: "Miracu",
    category: "Aesthetic",
    subcategory: "Aesthetic",
    description: "Ultra-thin medical-grade sutures, formulated with a polydioxanone (PDO)material that is naturally and safely absorbed by the body over time while simultaneously stimulating the body's natural production of collagen. Minimally invasive procedure, and short recovery time.",
    features: [
      "Press Cut Method PDO dissolvable thread.",
      "No heat treatment for stronger, consistent barbs.",
      "Skin revitalization and volumizing effect.",
      "Used for rejuvenation and local firming.",
      "Screw, Power Cog, Power Fixation, and Double Screw options.",
      "Targets marionette lines and deep wrinkles.",
      "High-polymer coated PDO thread.",
      "Anchor tip cannula for strong muscle fixation.",
      "Provides powerful lifting and long-lasting support.",
    ],
    images: ["/images/products/Aesthetic/Aesthetic/Miracu/1.png"],
  },
  {
    id: "new-melan-pro",
    name: "New Melan Pro",
    brand: "New Melan",
    category: "Aesthetic",
    subcategory: "Aesthetic",
    description: "Is a perfect and powerful combination of depigmenting actives, with potent antioxidant activity. Exclusive use in the office.  The mask's assets are combined to allow a powerful control and inhibition of melanin synthesis, intervening in the pre-synthesis processes, directly inhibiting the tyrosinase enzyme, degranulating the intra-keratinocyte pigment and favoring the epidermis turnover and the elimination of pigmented cells.",
    features: [
      "Depigmenting and antioxidant action.",
      "Inhibits melanin synthesis and tyrosinase.",
      "Promotes pigment elimination and skin turnover.",
    ],
    images: ["/images/products/Aesthetic/Aesthetic/New Melan/3.png"],
  },
  {
    id: "new-melan-day-night",
    name: "New Melan Day & Night",
    brand: "New Melan",
    category: "Aesthetic",
    subcategory: "Aesthetic",
    description: "This is the STAR of the treatment, for home use, this cream will achive and maintain the desired results. Combined with TD and PRO, applied by physician, the result will be obtained much faster.  Is the synergistic combination of several assets, simultaneously blocking the different stages that are related in the formation of Melasma. Acts in several stages of melanogenesis, tyrosinase. the process of oxidation of tyrosine and the formation of melanin. It acts at the level of melanocytes, and melanosomes superficial layers of the skin.",
    features: [
      "Home-use cream for maintaining treatment results.",
      "Synergistic action with professional treatments (TD and PRO).",
      "Blocks multiple stages of melasma formation.",
      "Inhibits melanogenesis and tyrosinase activity.",
      "Reduces melanin formation in melanocytes and melanosomes.",
    ],
    images: ["/images/products/Aesthetic/Aesthetic/New Melan/1.png"],
  },
  {
    id: "new-melan-intimate",
    name: "New Melan Intimate",
    brand: "New Melan",
    category: "Aesthetic",
    subcategory: "Aesthetic",
    description: "The most effective solution for depigmenting delicate and intimate areas like armpit, vulva, scrotum and anus, for home use, but, combined with TD and PRO, applied by physician, the results will be obtained much faster. Depigmenting activity is generated bythe acceleration of the phaeomelanin pathway and by the biochemical reduction of the deposited pigment.",
    features: [
      "Effective for depigmenting delicate and intimate areas.",
      "Suitable for home use.",
      "Faster results when combined with TD and PRO treatments.",
      "Accelerates phaeomelanin pathway.",
    ],
    images: ["/images/products/Aesthetic/Aesthetic/New Melan/2.png"],
  },
  {
    id: "preime-ha-3.5",
    name: "Preime HA 3.5",
    brand: "Preime",
    category: "Aesthetic",
    subcategory: "Aesthetic",
    description: "HA 3.5 Dual Hydrating solution is formulated to help restore volume, minimize the appearance of wrinkles, and boost hydration.",
    features: [

    ],
    images: ["/images/products/Aesthetic/Aesthetic/Preime/Advance Components/1.png"],
  },

  {
    id: "preime-hyaluronidase",
    name: "Preime HYALURONIDASE",
    brand: "Preime",
    category: "Aesthetic",
    subcategory: "Aesthetic",
    description: "HYALURONIDASE,  HA Rebalancing Solution helps to catalyse the degradation of hyaluronic acid and support skin care HA complications.",
    features: [

    ],
    images: ["/images/products/Aesthetic/Aesthetic/Preime/Advance Components/2.png"],
  },

  {
    id: "preime-ascorbic-acid-nt",
    name: "Preime ASCORBIC ACID + NT",
    brand: "Preime",
    category: "Aesthetic",
    subcategory: "Aesthetic",
    description: "Ascorbic Acid + NT Antioxidant Radiance solution formulated to improve the appearance of photo damaged and dull skin. It helps to protect against free radicals and restore the radiance of the skin.",
    features: [

    ],
    images: ["/images/products/Aesthetic/Aesthetic/Preime/Cocktails/1.png"],
  },

  {
    id: "preime-glutathione-b3",
    name: "Preime GLUTATHIONE +B3",
    brand: "Preime",
    category: "Aesthetic",
    subcategory: "Aesthetic",
    description: "GLUTATHIONE + B3 is a Brightening Solution formulated to improve the visible signs of aging, brighten skin complexion and  reduce the appearance of dark spots.",
    features: [

    ],
    images: ["/images/products/Aesthetic/Aesthetic/Preime/Cocktails/2.png"],
  },

  {
    id: "preime-ppc",
    name: "Preime PPC",
    brand: "Preime",
    category: "Aesthetic",
    subcategory: "Aesthetic",
    description: "PPC + Deox Contouring Solution is formulated to reduce the appearance of cellulite and providing smoother and firmer looking skin.",
    features: [

    ],
    images: ["/images/products/Aesthetic/Aesthetic/Preime/Cocktails/3.png"],
  },

  {
    id: "preime-retinol-tc",
    name: "Preime RETINOL + TC",
    brand: "Preime",
    category: "Aesthetic",
    subcategory: "Aesthetic",
    description: "Retinol + TC Retexture Finish solution is formulated to support skin cells turnover and to reduce and rejuvenate the skin.",
    features: [

    ],
    images: ["/images/products/Aesthetic/Aesthetic/Preime/Cocktails/4.png"],
  },

  {
    id: "preime-skin-lift",
    name: "Preime SKIN LIFT",
    brand: "Preime",
    category: "Aesthetic",
    subcategory: "Aesthetic",
    description: "Skin Lift Multipeptide Lifting Solution is formulated to visibly firm and tone the skin. It helps to reduce the appearance of fine lines and wrinkles.",
    features: [

    ],
    images: ["/images/products/Aesthetic/Aesthetic/Preime/Cocktails/5.png"],
  },

  {
    id: "preime-skin-renew",
    name: "Preime SKIN RENEW",
    brand: "Preime",
    category: "Aesthetic",
    subcategory: "Aesthetic",
    description: "Skin Renew solution is formulated to nourish dehydrated and environmentally stressed skin, it helps plump skin and improves skins radiance.",
    features: [

    ],
    images: ["/images/products/Aesthetic/Aesthetic/Preime/Cocktails/6.png"],
  },

  {
    id: "preime-txa-bright",
    name: "Preime TXA BRIGHT",
    brand: "Preime",
    category: "Aesthetic",
    subcategory: "Aesthetic",
    description: "TXA Bright Melablock Brightening Solution helps to improve irregularities in skin tone, restoring radiance and moisture to the skin.",
    features: [

    ],
    images: ["/images/products/Aesthetic/Aesthetic/Preime/Cocktails/7.png"],
  },

  {
    id: "preime-pdrn-booster",
    name: "Preime PDRN Booster",
    brand: "Preime",
    category: "Aesthetic",
    subcategory: "Aesthetic",
    description: "PDRN Booster  is Nucleotide Rejuvenating Solution formulated to help support skin regenration, rejuvenation and to improve the appearance of wrinkles and skin imperfections..",
    features: [

    ],
    images: ["/images/products/Aesthetic/Aesthetic/Preime/Human Exosome/1.png"],
  },

  {
    id: "preime-pure-bright",
    name: "Preime Pure Bright",
    brand: "Preime",
    category: "Aesthetic",
    subcategory: "Aesthetic",
    description: "Pure Bright Exosome Brightening Solution is formulated to unveil the power of skin regeneration and radiance. This solution combines exosomes and advanced brightening actives to enhance luminosity and refine complexion, promoting youthful skin appearance.",
    features: [

    ],
    images: ["/images/products/Aesthetic/Aesthetic/Preime/Human Exosome/2.png"],
  },
  
  {
    id: "preime-pure",
    name: "Preime Pure",
    brand: "Preime",
    category: "Aesthetic",
    subcategory: "Aesthetic",
    description: "Pure Technology™ is a unique, advanced process of a revolutionary skincare line, focusing on unmatched purity and potency that supports skin regeneration, and is the foundation of a diverse product family, each meticulously crafted to meet the latest skincare needs in regenerative aesthetics.",
    features: [

    ],
    images: ["/images/products/Aesthetic/Aesthetic/Preime/Human Exosome/3.png"],
  },

  {
    id: "preime-renew",
    name: "Preime Renew",
    brand: "Preime",
    category: "Aesthetic",
    subcategory: "Aesthetic",
    description: "Renew Bio - Exosome Solution, formulated with advanced Pure Technology™, harnesses the power of plant exosomes to support skin renewal. This potent solution supports natural rejuvenation, refining skin texture and enhancing radiance for a visibly transformed complexion.",
    features: [

    ],
    images: ["/images/products/Aesthetic/Aesthetic/Preime/Human Exosome/4.png"],
  },

  {
    id: "preime-hair-scalp-booster",
    name: "Preime HAIR & SCALP BOOSTER",
    brand: "Preime",
    category: "Aesthetic",
    subcategory: "Aesthetic",
    description: "Hair & Scalp Booster solution helps to support the health both the hair folicle and the hair bulb. The combination of stimulating and protective actives helps to promote healthy scalp.",
    features: [

    ],
    images: ["/images/products/Aesthetic/Aesthetic/Preime/Scalp/1.png"],
  },

  // ==================== AESTHETIC - MIA FEMTECH ====================
  {
    id: "mia-femtech",
    name: "Mia Femtech",
    brand: "Mia Femtech",
    category: "Aesthetic",
    subcategory: "Breast Harmonization",
    description: "A minimally invasive breast harmonization experience with Breast Tissue Preservation utilizing a transaxillary approach. Featuring the first ever injectable implants for 1 to 2 cups up, designed for an authentic natural look & feel. Available exclusively to Mia Femtech™ certified plastic surgeons only.",
    features: [
      "Designed for a natural look & feel.",
      "90-minute procedure with no need for general anesthesia.",
      "Get back to life on the same day.",
      "Minimal scar, hidden in each armpit.",
      "Breast Tissue Preservation — no damage to tissue.",
      "SmoothSilk® Ergonomix2® Diamond® with Zen® technology.",
      "Available exclusively to certified Mia Femtech™ plastic surgeons.",
    ],
    images: [
      "/images/products/Aesthetic/Mia/listing.jpg",
      "/images/products/Aesthetic/Mia/1.jpg",
      "/images/products/Aesthetic/Mia/2.jpg",
    ],
  },

  // ==================== AESTHETIC - ONAD ====================
  {
    id: "onad",
    name: "ŎNAD",
    brand: "ŎNAD",
    category: "Aesthetic",
    subcategory: "NAD+ Regenerative Care",
    description: "ŎNAD is the world's first NAD+ regenerative skincare and aesthetic range — featuring ETERNAVIA (Face Solution), LEVRA (Lip Booster) and PRIVIA (Intimate Area Care). Powered by bio-identical NAD+ to stimulate dermal regeneration, collagen production and cellular renewal.",
    features: [
      "ETERNAVIA — first & only NAD+ Face Solution worldwide.",
      "LEVRA — injection-grade lip booster with no fillers.",
      "PRIVIA — intimate area care addressing vulvovaginal health.",
      "Powered by bio-identical NAD+ delivered directly to the dermis.",
      "Backed by 40+ years of research in aging and DNA repair.",
      "Activates mitochondrial function and fibroblast activity.",
    ],
    images: [
      "/images/products/Aesthetic/Eternavia/1.jpg",
      "/images/products/Aesthetic/Levra/1.jpg",
      "/images/products/Aesthetic/Privia/1.jpg",
    ],
  },

  // ==================== AESTHETIC - BREAST IMPLANTS ====================
  {
    id: "breast-implants-ergonomix2",
    name: "Ergonomix2",
    brand: "Motiva",
    category: "Aesthetic",
    subcategory: "Breast Implants",
    description: "Designed for improved ergonomy and even softer implant. Available exclusively with JOY®.",
    features: [
      "A safer choice.",
      "Real touch and feel.",
      "Improved support programs.",
      "Least incidents of rapture, capsular contraction, and late seroma.",
    ],
    images: [
      "/images/products/Aesthetic/Breast Implants/1.jpg",
    ],
  },

  {
    id: "breast-implants-ergonomix",
    name: "Ergonomix",
    brand: "Motiva",
    category: "Aesthetic",
    subcategory: "Breast Implants",
    description: "Designed to mimic the look, feel, and movement of natural breast tissue.",
    features: [
      "A safer choice.",
      "Real touch and feel.",
      "Improved support programs.",
      "Least incidents of rapture, capsular contraction, and late seroma.",
    ],
    images: [
      "/images/products/Aesthetic/Breast Implants/2.jpg",
    ],
  },

  {
    id: "breast-implants-motiva-round",
    name: "Motiva Round",
    brand: "Motiva",
    category: "Aesthetic",
    subcategory: "Breast Implants",
    description: "Balanced softness and firmness, with a round upper breast.",
    features: [
      "A safer choice.",
      "Real touch and feel.",
      "Improved support programs.",
      "Least incidents of rapture, capsular contraction, and late seroma.",
    ],
    images: [
      "/images/products/Aesthetic/Breast Implants/3.jpg",
    ],
  },

  

  // ==================== AESTHETIC - HA FILLERS ====================
  {
    id: "restylane-classyc",
    name: "Restylane Classyc",
    brand: "Restylane",
    category: "Aesthetic",
    subcategory: "HA Fillers",
    description: "Hyaluronic acid, stabilized 20 mg/ml Lidocaine hydrochloride 3mg/ml Intended for facial tissue augmentation.",
    banner: "/images/activities/events/restylane-reveal/3.jpg",
    bannerTagline: "Natural-looking results. Trusted by millions worldwide.",
    features: [],
    images: ["/images/products/Aesthetic/HA Fillers/Restylane/1.png"],
    beforeAfter: [
      { before: "/images/activities/workshops/restylane-dr-rana-morsi/1.jpg", after: "/images/activities/workshops/restylane-dr-rana-morsi/10.jpg", caption: "Facial tissue augmentation with Restylane Classyc" },
    ],
  },
  {
    id: "restylane-defyne",
    name: "Restylane Defyne",
    brand: "Restylane",
    category: "Aesthetic",
    subcategory: "HA Fillers",
    description: "Cross-linked hyaluronic acid 20 mg/ml Lidocaine hydrochloride 3 mg/ml Intended to augment the volume of facial tissues",
    banner: "/images/activities/events/restylane-reveal/12.jpg",
    bannerTagline: "Deep facial wrinkles and folds. Defined. Natural.",
    features: [],
    images: ["/images/products/Aesthetic/HA Fillers/Restylane/2.png"],
    beforeAfter: [
      { before: "/images/activities/workshops/restylane-filler-workshop-rana-morsi/1.jpg", after: "/images/activities/workshops/restylane-filler-workshop-rana-morsi/12.jpg", caption: "Nasolabial fold correction with Restylane Defyne" },
    ],
  },
  {
    id: "restylane-kysse",
    name: "Restylane Kysse",
    brand: "Restylane",
    category: "Aesthetic",
    subcategory: "HA Fillers",
    description: "Cross-linked hyaluronic acid 20 mg/ml Lidocaine hydrochloride 3 mg/ml Intended to restore or augment the volume of the lips.",
    banner: "/images/activities/events/restylane-reveal/25.jpg",
    bannerTagline: "Fuller, natural-looking lips. Designed with movement in mind.",
    features: [
      "Lip enhancement",
      "Natural texture",
      "Smooth application",
      "Minimal swelling",
    ],
    images: ["/images/products/Aesthetic/HA Fillers/Restylane/3.png"],
    beforeAfter: [
      { before: "/images/activities/workshops/restylane-filler-workshop-micheline-chalouhi/1.jpg", after: "/images/activities/workshops/restylane-filler-workshop-micheline-chalouhi/9.jpg", caption: "Lip augmentation with Restylane Kysse" },
    ],
  },
  {
    id: "restylane-lyft",
    name: "Restylane Lyft",
    brand: "Restylane",
    category: "Aesthetic",
    subcategory: "HA Fillers",
    description: "Hyaluronic acid, stabilized 20 mg/ml Lidocaine hydrochloride 3mmg/ml Intended for facial tissue augmentation.",
    banner: "/images/activities/events/restylane-reveal/40.jpg",
    bannerTagline: "Cheek augmentation. Restored. Elevated.",
    features: [],
    images: ["/images/products/Aesthetic/HA Fillers/Restylane/4.png"],
    beforeAfter: [
      { before: "/images/activities/workshops/restylane-filler-workshop-islaam-alshawadfy-01/1.jpg", after: "/images/activities/workshops/restylane-filler-workshop-eslam-alshawadfy-01/17.jpg", caption: "Midface volume restoration with Restylane Lyft" },
    ],
  },
  {
    id: "restylane-volyme",
    name: "Restylane Volyme",
    brand: "Restylane",
    category: "Aesthetic",
    subcategory: "HA Fillers",
    description: "Cross-linked hyaluronic acid 20 mg/ml Lidocaine hydrochloride 3 mg/ml Intended to augment the volume of facial tissues",
    banner: "/images/activities/events/restylane-reveal/55.jpg",
    bannerTagline: "Volume. Definition. Natural beauty.",
    features: [],
    images: ["/images/products/Aesthetic/HA Fillers/Restylane/4.png"],
    beforeAfter: [
      { before: "/images/activities/workshops/restylane-filler-workshop-mona-salem/1.jpg", after: "/images/activities/workshops/restylane-filler-workshop-reham-ismail/22.jpg", caption: "Facial volume augmentation with Restylane Volyme" },
    ],
  },
  {
    id: "restylane-skinbooster-vital",
    name: "Restylane Skinbooster Vital",
    brand: "Restylane",
    category: "Aesthetic",
    subcategory: "HA Fillers",
    description: "Hyaluronic acid, stabilized 20 mg/ml Lidocaine hydrochloride 3mg/ml Intended to restore skin hydrobalance, improve structure and elasticity of the skin.",
    banner: "/images/activities/events/restylane-reveal/65.jpg",
    bannerTagline: "Hydration from within. Radiant, healthy skin.",
    features: [],
    images: ["/images/products/Aesthetic/HA Fillers/Restylane/6.png"],
    beforeAfter: [
      { before: "/images/activities/workshops/restylane-masterclass-dr-ishaan-ramkisson/1.jpg", after: "/images/activities/workshops/restylane-masterclass-dr-ishaan-ramkisson/15.jpg", caption: "Skin hydration boost with Restylane Skinbooster Vital" },
    ],
  },
  {
    id: "restylane-skinbooster-vital-light",
    name: "Restylane Skinbooster Vital Light",
    brand: "Restylane",
    category: "Aesthetic",
    subcategory: "HA Fillers",
    description: "Hyaluronic acid, stabilized 12 mg/ml Lidocaine hydrochloride 3mmg/ml Intended to restore skin hydrobalance, improve structure and elasticity of the skin.",
    banner: "/images/activities/events/restylane-reveal/70.jpg",
    bannerTagline: "Lighter formula. Softer results. Pure radiance.",
    features: [],
    images: ["/images/products/Aesthetic/HA Fillers/Restylane/5.png"],
    beforeAfter: [
      { before: "/images/activities/workshops/restylane-filler-workshop-ishaan-ramkisson/1.jpg", after: "/images/activities/workshops/restylane-filler-workshop-ishaan-ramkisson/4.jpg", caption: "Skin texture improvement with Restylane Skinbooster Vital Light" },
    ],
  },

  // ==================== AESTHETIC - PROFESSIONAL/RETAIL PRODUCTS ====================
  {
    id: "preime-booster-activator",
    name: "Preime BOOSTER ACTIVATOR",
    brand: "Preime",
    category: "Aesthetic",
    subcategory: "Professional - Retail Products",
    description: "BOOSTER ACTIVATOR is a hydrating and soothing serum designed to support skin recovery.  Its soft texture ensures optimal comfort for the skin. ",
    features: [
    ],
    images: ["/images/products/Aesthetic/Professional - Retail Products/1.png"],
  },
  {
    id: "preime-natural-cleanser",
    name: "Preime NATURAL CLEANSER ",
    brand: "Preime",
    category: "Aesthetic",
    subcategory: "Professional - Retail Products",
    description: "NATURAL CLEANSER is gentle rebalancing cleanser suitable for all skin types. Specifically formulated to cleanse the skin on the face, neck, and decolletage, it ensures a throrough and refreshing cleaning experience. ",
    features: [
    ],
    images: ["/images/products/Aesthetic/Professional - Retail Products/2.png"],
  },
  {
    id: "preime-pdrn-booster-serum",
    name: "Preime PDRN BOOSTER SERUM ",
    brand: "Preime",
    category: "Aesthetic",
    subcategory: "Professional - Retail Products",
    description: "PDRN BOOSTER SERUM  Rejuvenating face serum is formulated to boost skin rejuvenation, balance skin tone  and improve skin imperfections. Light texture with powerful actives for daily use.",
    features: [
    ],
    images: ["/images/products/Aesthetic/Professional - Retail Products/3.png"],
  },
  {
    id: "preime-pdrn-toner",
    name: "Preime PDRN TONER",
    brand: "Preime",
    category: "Aesthetic",
    subcategory: "Professional - Retail Products",
    description: "PDRN TONER is a gentle delicately soothing toner designed to support skin rejuvenation, enhance radiance, and promote softness.",
    features: [
    ],
    images: ["/images/products/Aesthetic/Professional - Retail Products/4.png"],
  },
  {
    id: "preime-pure-elixir",
    name: "Preime PURE ELIXIR",
    brand: "Preime",
    category: "Aesthetic",
    subcategory: "Professional - Retail Products",
    description: "PURE ELIXIR FACE Serum is specially formulated to promote skin regeneration and brightening, and to help reduce the appearance of fine lines and wrinkles. This serum is  a new-generation formula that combines exosomes for skin regeneration, together with brightening agents and plant extracts to even skin tone and to help replenish the skin.",
    features: [
    ],
    images: ["/images/products/Aesthetic/Professional - Retail Products/5.png"],
  },
  {
    id: "preime-txa-bright-serum",
    name: "Preime TXA BRIGHT SERUM",
    brand: "Preime",
    category: "Aesthetic",
    subcategory: "Professional - Retail Products",
    description: "TXA BRIGHT SERUM Melablock Brightening Serum contains potent actives to support skin brightening and reduce appearance of dark spots.",
    features: [
    ],
    images: ["/images/products/Aesthetic/Professional - Retail Products/6.png"],
  },
];

export const productCategories = {
  Machines: {
    name: "Medical Machines",
    description: "Advanced medical and aesthetic equipment for professional use",
    subcategories: ["Aesthetic", "Facial", "Laser", "Slimming", "Support"],
  },
  Aesthetic: {
    name: "Aesthetic Products",
    description: "Premium aesthetic and cosmetic products",
    subcategories: [
      "Aesthetic",
      "Breast Implants",
      "HA Fillers",
      "Professional - Retail Products",
    ],
  },
};
